#!/bin/bash

echo "🔧 LinkedIn Share Button Troubleshooting"
echo "======================================="

echo "📋 Steps to fix the LinkedIn share button visibility issue:"
echo ""
echo "1. 🧹 Clear Browser Cache:"
echo "   - Press Ctrl+Shift+R (Windows/Linux) or Cmd+Shift+R (Mac)"
echo "   - Or go to Developer Tools (F12) → Network tab → Check 'Disable cache'"
echo ""
echo "2. 🔄 Hard Refresh the Page:"
echo "   - Close the browser tab completely"
echo "   - Reopen the dashboard"
echo "   - Navigate to Image Gen section"
echo ""
echo "3. 🔍 Check Console for Debug Messages:"
echo "   - Open Developer Tools (F12)"
echo "   - Go to Console tab"
echo "   - Look for: 'ImageGenerator component rendered with LinkedIn share functionality'"
echo "   - Generate an image and look for: 'LinkedIn share button clicked for image: [id]'"
echo ""
echo "4. 🧪 Test the Debug Page:"
echo "   - Visit: http://localhost:3000/debug-linkedin"
echo "   - This will show a test LinkedIn button"
echo ""
echo "5. 🔧 If still not working:"
echo "   - Check if the component is being cached by Next.js"
echo "   - Try restarting the development server"
echo "   - Check browser console for any JavaScript errors"
echo ""
echo "✅ The LinkedIn share button should appear below each generated image"
echo "   as a blue button with LinkedIn icon and 'Share to LinkedIn' text"
